
const ScreenVol_Buttons_Round: array[008] of TButton_RoundPtr;  code; external;
const ScreenVol_Labels:        array[011] of TLabelPtr;         code; external;
const ScreenVol_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenVol_Boxes:         array[002] of TBoxPtr;           code; external;
const ScreenVol_CBoxes:        array[002] of TCBoxPtr;          code; external;
const ScreenVol_Lines:         array[001] of TLinePtr;          code; external;
const ScreenVol_CLines:        array[003] of TCLinePtr;         code; external;
const ScreenVol_EveScrollBars: array[011] of TEveScrollbarPtr;  code; external;

var   ScreenVol: TScreen; external;


var   Box22: TBox; external;

var   ButtonRound159_Caption: string[4];     external;
var   ButtonRound159_OnDown:  TEvent;        external;
var   ButtonRound159:         TButton_Round; external;

var   ButtonRound23_Caption: string[8];     external;
var   ButtonRound23_OnDown:  TEvent;        external;
var   ButtonRound23:         TButton_Round; external;

var   ButtonRound22_Caption: string[7];     external;
var   ButtonRound22_OnDown:  TEvent;        external;
var   ButtonRound22:         TButton_Round; external;

var   ButtonRound21_Caption: string[8];     external;
var   ButtonRound21_OnDown:  TEvent;        external;
var   ButtonRound21:         TButton_Round; external;

var   ButtonRound20_Caption: string[4];     external;
var   ButtonRound20_OnDown:  TEvent;        external;
var   ButtonRound20:         TButton_Round; external;

var   ButtonRound19_Caption: string[7];     external;
var   ButtonRound19_OnDown:  TEvent;        external;
var   ButtonRound19:         TButton_Round; external;

const Label1_Caption: string[7]; code; external;
const Label1:         TCLabel;   code; external;

var   EveScrollBar3_OnPress: TEvent;        external;
var   EveScrollBar3:         TEveScrollbar; external;

var   Label14_Caption: string[10]; external;
var   Label14:         TLabel;     external;

var   EveScrollBar4_OnPress: TEvent;        external;
var   EveScrollBar4:         TEveScrollbar; external;

var   Label15_Caption: string[8]; external;
var   Label15:         TLabel;    external;

var   EveScrollBar5_OnPress: TEvent;        external;
var   EveScrollBar5:         TEveScrollbar; external;

var   Label16_Caption: string[13]; external;
var   Label16:         TLabel;     external;

var   EveScrollBar6_OnPress: TEvent;        external;
var   EveScrollBar6:         TEveScrollbar; external;

var   Label17_Caption: string[13]; external;
var   Label17:         TLabel;     external;

var   EveScrollBar7_OnPress: TEvent;        external;
var   EveScrollBar7:         TEveScrollbar; external;

var   Label18_Caption: string[13]; external;
var   Label18:         TLabel;     external;

var   EveScrollBar8_OnPress: TEvent;        external;
var   EveScrollBar8:         TEveScrollbar; external;

var   Label19_Caption: string[14]; external;
var   Label19:         TLabel;     external;

var   EveScrollBar9_OnPress: TEvent;        external;
var   EveScrollBar9:         TEveScrollbar; external;

var   Label20_Caption: string[11]; external;
var   Label20:         TLabel;     external;

var   EveScrollBar10_OnPress: TEvent;        external;
var   EveScrollBar10:         TEveScrollbar; external;

var   Label21_Caption: string[11]; external;
var   Label21:         TLabel;     external;

var   EveScrollBar11_OnPress: TEvent;        external;
var   EveScrollBar11:         TEveScrollbar; external;

var   Label23_Caption: string[11]; external;
var   Label23:         TLabel;     external;

var   EveScrollBar12_OnPress: TEvent;        external;
var   EveScrollBar12:         TEveScrollbar; external;

var   Label24_Caption: string[12]; external;
var   Label24:         TLabel;     external;

var   EveScrollBar14_OnPress: TEvent;        external;
var   EveScrollBar14:         TEveScrollbar; external;

var   Label26_Caption: string[13]; external;
var   Label26:         TLabel;     external;

var   Line9: TLine; external;

const Box3: TCBox; code; external;

const Line5: TCLine; code; external;

const Line4: TCLine; code; external;

var   Box18: TBox; external;

var   ButtonRound56_Caption: string[7];     external;
var   ButtonRound56_OnDown:  TEvent;        external;
var   ButtonRound56:         TButton_Round; external;

var   ButtonRound102_Caption: string[9];     external;
var   ButtonRound102_OnDown:  TEvent;        external;
var   ButtonRound102:         TButton_Round; external;

const Box19: TCBox; code; external;

const Line10: TCLine; code; external;
const ScreenVol_Buttons_Round: array[008] of TButton_RoundPtr;  code; external;
const ScreenVol_Labels:        array[011] of TLabelPtr;         code; external;
const ScreenVol_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenVol_Boxes:         array[002] of TBoxPtr;           code; external;
const ScreenVol_CBoxes:        array[002] of TCBoxPtr;          code; external;
const ScreenVol_Lines:         array[001] of TLinePtr;          code; external;
const ScreenVol_CLines:        array[003] of TCLinePtr;         code; external;
const ScreenVol_EveScrollBars: array[011] of TEveScrollbarPtr;  code; external;


const ScreenEqu_Buttons_Round: array[009] of TButton_RoundPtr;  code; external;
const ScreenEqu_Labels:        array[009] of TLabelPtr;         code; external;
const ScreenEqu_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenEqu_Boxes:         array[002] of TBoxPtr;           code; external;
const ScreenEqu_CBoxes:        array[002] of TCBoxPtr;          code; external;
const ScreenEqu_Boxes_Round:   array[001] of TBox_RoundPtr;     code; external;
const ScreenEqu_CLines:        array[004] of TCLinePtr;         code; external;
const ScreenEqu_EveScrollBars: array[009] of TEveScrollbarPtr;  code; external;

var   ScreenEqu: TScreen; external;


var   Box4: TBox; external;

var   ButtonRound160_Caption: string[7];     external;
var   ButtonRound160_OnDown:  TEvent;        external;
var   ButtonRound160:         TButton_Round; external;

var   ButtonRound32_Caption: string[4];     external;
var   ButtonRound32_OnDown:  TEvent;        external;
var   ButtonRound32:         TButton_Round; external;

var   ButtonRound31_Caption: string[8];     external;
var   ButtonRound31_OnDown:  TEvent;        external;
var   ButtonRound31:         TButton_Round; external;

var   ButtonRound30_Caption: string[7];     external;
var   ButtonRound30_OnDown:  TEvent;        external;
var   ButtonRound30:         TButton_Round; external;

var   ButtonRound29_Caption: string[8];     external;
var   ButtonRound29_OnDown:  TEvent;        external;
var   ButtonRound29:         TButton_Round; external;

var   ButtonRound28_Caption: string[4];     external;
var   ButtonRound28_OnDown:  TEvent;        external;
var   ButtonRound28:         TButton_Round; external;

var   BoxRound22: TBox_Round; external;

var   ButtonRound54_Caption: string[10];    external;
var   ButtonRound54_OnDown:  TEvent;        external;
var   ButtonRound54:         TButton_Round; external;

var   EveScrollBar13_OnPress: TEvent;        external;
var   EveScrollBar13:         TEveScrollbar; external;

var   Label25_Caption: string[8]; external;
var   Label25:         TLabel;    external;

var   EveScrollBar15_OnPress: TEvent;        external;
var   EveScrollBar15:         TEveScrollbar; external;

var   Label27_Caption: string[9]; external;
var   Label27:         TLabel;    external;

var   EveScrollBar16_OnPress: TEvent;        external;
var   EveScrollBar16:         TEveScrollbar; external;

var   Label28_Caption: string[10]; external;
var   Label28:         TLabel;     external;

var   EveScrollBar25_OnPress: TEvent;        external;
var   EveScrollBar25:         TEveScrollbar; external;

var   Label29_Caption: string[9]; external;
var   Label29:         TLabel;    external;

var   EveScrollBar26_OnPress: TEvent;        external;
var   EveScrollBar26:         TEveScrollbar; external;

var   Label30_Caption: string[8]; external;
var   Label30:         TLabel;    external;

var   EveScrollBar27_OnPress: TEvent;        external;
var   EveScrollBar27:         TEveScrollbar; external;

var   Label31_Caption: string[11]; external;
var   Label31:         TLabel;     external;

var   EveScrollBar28_OnPress: TEvent;        external;
var   EveScrollBar28:         TEveScrollbar; external;

var   Label41_Caption: string[12]; external;
var   Label41:         TLabel;     external;

var   EveScrollBar33_OnPress: TEvent;        external;
var   EveScrollBar33:         TEveScrollbar; external;

var   Label43_Caption: string[11]; external;
var   Label43:         TLabel;     external;

var   EveScrollBar34_OnPress: TEvent;        external;
var   EveScrollBar34:         TEveScrollbar; external;

var   Label44_Caption: string[9]; external;
var   Label44:         TLabel;    external;

const Label45_Caption: string[9]; code; external;
const Label45:         TCLabel;   code; external;

const Box21: TCBox; code; external;

const Line6: TCLine; code; external;

const Line7: TCLine; code; external;

var   Box2: TBox; external;

var   ButtonRound24_Caption: string[7];     external;
var   ButtonRound24_OnDown:  TEvent;        external;
var   ButtonRound24:         TButton_Round; external;

var   ButtonRound25_Caption: string[9];     external;
var   ButtonRound25_OnDown:  TEvent;        external;
var   ButtonRound25:         TButton_Round; external;

const Box6: TCBox; code; external;

const Line3: TCLine; code; external;

const Line2: TCLine; code; external;
const ScreenEqu_Buttons_Round: array[009] of TButton_RoundPtr;  code; external;
const ScreenEqu_Labels:        array[009] of TLabelPtr;         code; external;
const ScreenEqu_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenEqu_Boxes:         array[002] of TBoxPtr;           code; external;
const ScreenEqu_CBoxes:        array[002] of TCBoxPtr;          code; external;
const ScreenEqu_Boxes_Round:   array[001] of TBox_RoundPtr;     code; external;
const ScreenEqu_CLines:        array[004] of TCLinePtr;         code; external;
const ScreenEqu_EveScrollBars: array[009] of TEveScrollbarPtr;  code; external;


const ScreenEdit_Buttons_Round: array[006] of TButton_RoundPtr;  code; external;
const ScreenEdit_CLabels:       array[002] of TCLabelPtr;        code; external;
const ScreenEdit_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenEdit_CBoxes:        array[001] of TCBoxPtr;          code; external;
const ScreenEdit_Boxes_Round:   array[001] of TBox_RoundPtr;     code; external;
const ScreenEdit_CBoxes_Round:  array[001] of TCBox_RoundPtr;    code; external;
const ScreenEdit_CLines:        array[001] of TCLinePtr;         code; external;
const ScreenEdit_EveKeys:       array[004] of TEveKeysPtr;       code; external;
const ScreenEdit_EveTexts:      array[002] of TEveTextPtr;       code; external;

var   ScreenEdit: TScreen; external;


var   Box20: TBox; external;

var   ButtonRound158_Caption: string[7];     external;
var   ButtonRound158_OnDown:  TEvent;        external;
var   ButtonRound158:         TButton_Round; external;

const BoxRound2: TCBox_Round; code; external;

var   ButtonRound33_Caption: string[4];     external;
var   ButtonRound33_OnDown:  TEvent;        external;
var   ButtonRound33:         TButton_Round; external;

var   ButtonRound34_Caption: string[8];     external;
var   ButtonRound34_OnDown:  TEvent;        external;
var   ButtonRound34:         TButton_Round; external;

var   ButtonRound35_Caption: string[7];     external;
var   ButtonRound35_OnDown:  TEvent;        external;
var   ButtonRound35:         TButton_Round; external;

var   ButtonRound36_Caption: string[8];     external;
var   ButtonRound36_OnDown:  TEvent;        external;
var   ButtonRound36:         TButton_Round; external;

var   ButtonRound37_Caption: string[4];     external;
var   ButtonRound37_OnDown:  TEvent;        external;
var   ButtonRound37:         TButton_Round; external;

const Box5: TCBox; code; external;

const Line8: TCLine; code; external;

var   EveKeysRow3_Caption: string[3]; external;
var   EveKeysRow3_OnDown:  TEvent;    external;
var   EveKeysRow3:         TEveKeys;  external;

var   EveKeysRow2_Caption: string[3]; external;
var   EveKeysRow2_OnDown:  TEvent;    external;
var   EveKeysRow2:         TEveKeys;  external;

var   EveKeysRow1_Caption: string[5]; external;
var   EveKeysRow1_OnDown:  TEvent;    external;
var   EveKeysRow1:         TEveKeys;  external;

var   EveKeysRow4_Caption: string[4]; external;
var   EveKeysRow4_OnDown:  TEvent;    external;
var   EveKeysRow4:         TEveKeys;  external;

var   EveTextCommand_Caption: string[15]; external;
var   EveTextCommand:         TEveText;   external;

const Label72_Caption: string[7]; code; external;
const Label72:         TCLabel;   code; external;

var   BoxRoundResult: TBox_Round; external;

var   EveTextResult_Caption: string[7]; external;
var   EveTextResult:         TEveText;  external;

const Label73_Caption: string[6]; code; external;
const Label73:         TCLabel;   code; external;
const ScreenEdit_Buttons_Round: array[006] of TButton_RoundPtr;  code; external;
const ScreenEdit_CLabels:       array[002] of TCLabelPtr;        code; external;
const ScreenEdit_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenEdit_CBoxes:        array[001] of TCBoxPtr;          code; external;
const ScreenEdit_Boxes_Round:   array[001] of TBox_RoundPtr;     code; external;
const ScreenEdit_CBoxes_Round:  array[001] of TCBox_RoundPtr;    code; external;
const ScreenEdit_CLines:        array[001] of TCLinePtr;         code; external;
const ScreenEdit_EveKeys:       array[004] of TEveKeysPtr;       code; external;
const ScreenEdit_EveTexts:      array[002] of TEveTextPtr;       code; external;


const ScreenOrg_Buttons_Round: array[017] of TButton_RoundPtr;  code; external;
const ScreenOrg_CLabels:       array[004] of TCLabelPtr;        code; external;
const ScreenOrg_CCircles:      array[001] of TCCirclePtr;       code; external;
const ScreenOrg_CircleButtons: array[006] of TCircleButtonPtr;  code; external;
const ScreenOrg_Boxes:         array[002] of TBoxPtr;           code; external;
const ScreenOrg_CBoxes:        array[002] of TCBoxPtr;          code; external;
const ScreenOrg_Boxes_Round:   array[008] of TBox_RoundPtr;     code; external;
const ScreenOrg_Lines:         array[001] of TLinePtr;          code; external;
const ScreenOrg_CLines:        array[003] of TCLinePtr;         code; external;
const ScreenOrg_EveDials:      array[001] of TEveDialPtr;       code; external;
const ScreenOrg_EveSliders:    array[001] of TEveSliderPtr;     code; external;

var   ScreenOrg: TScreen; external;


var   Box15: TBox; external;

var   ButtonRound161_Caption: string[7];     external;
var   ButtonRound161_OnDown:  TEvent;        external;
var   ButtonRound161:         TButton_Round; external;

var   ButtonRound64_Caption: string[4];     external;
var   ButtonRound64_OnDown:  TEvent;        external;
var   ButtonRound64:         TButton_Round; external;

var   ButtonRound63_Caption: string[8];     external;
var   ButtonRound63_OnDown:  TEvent;        external;
var   ButtonRound63:         TButton_Round; external;

var   ButtonRound62_Caption: string[7];     external;
var   ButtonRound62_OnDown:  TEvent;        external;
var   ButtonRound62:         TButton_Round; external;

var   ButtonRound61_Caption: string[8];     external;
var   ButtonRound61_OnDown:  TEvent;        external;
var   ButtonRound61:         TButton_Round; external;

var   ButtonRound60_Caption: string[4];     external;
var   ButtonRound60_OnDown:  TEvent;        external;
var   ButtonRound60:         TButton_Round; external;

const Circle1: TCCircle; code; external;

var   Box11: TBox; external;

var   ButtonRound65_Caption: string[5];     external;
var   ButtonRound65_OnDown:  TEvent;        external;
var   ButtonRound65:         TButton_Round; external;

var   ButtonRound66_Caption: string[7];     external;
var   ButtonRound66_OnDown:  TEvent;        external;
var   ButtonRound66:         TButton_Round; external;

var   ButtonRound67_Caption: string[7];     external;
var   ButtonRound67_OnDown:  TEvent;        external;
var   ButtonRound67:         TButton_Round; external;

const Box10: TCBox; code; external;

var   EveSlider1_OnPress: TEvent;     external;
var   EveSlider1:         TEveSlider; external;

var   BoxRound24: TBox_Round; external;

var   BoxRound27: TBox_Round; external;

var   ButtonRound70_Caption: string[3];     external;
var   ButtonRound70_OnDown:  TEvent;        external;
var   ButtonRound70:         TButton_Round; external;

var   ButtonRound71_Caption: string[4];     external;
var   ButtonRound71_OnDown:  TEvent;        external;
var   ButtonRound71:         TButton_Round; external;

var   CircleButton13_Caption: string[2];     external;
var   CircleButton13_OnDown:  TEvent;        external;
var   CircleButton13:         TCircleButton; external;

var   CircleButton14_Caption: string[2];     external;
var   CircleButton14_OnDown:  TEvent;        external;
var   CircleButton14:         TCircleButton; external;

var   CircleButton15_Caption: string[2];     external;
var   CircleButton15_OnDown:  TEvent;        external;
var   CircleButton15:         TCircleButton; external;

var   CircleButton16_Caption: string[2];     external;
var   CircleButton16_OnDown:  TEvent;        external;
var   CircleButton16:         TCircleButton; external;

var   CircleButton17_Caption: string[2];     external;
var   CircleButton17_OnDown:  TEvent;        external;
var   CircleButton17:         TCircleButton; external;

var   CircleButton18_Caption: string[2];     external;
var   CircleButton18_OnDown:  TEvent;        external;
var   CircleButton18:         TCircleButton; external;

var   Line17: TLine; external;

const Line18: TCLine; code; external;

const Box12: TCBox; code; external;

var   BoxRound4: TBox_Round; external;

var   BoxRound13: TBox_Round; external;

var   ButtonRound38_Caption: string[9];     external;
var   ButtonRound38_OnDown:  TEvent;        external;
var   ButtonRound38:         TButton_Round; external;

var   ButtonRound39_Caption: string[9];     external;
var   ButtonRound39_OnDown:  TEvent;        external;
var   ButtonRound39:         TButton_Round; external;

const Line16: TCLine; code; external;

const Label2_Caption: string[2]; code; external;
const Label2:         TCLabel;   code; external;

const Label3_Caption: string[4]; code; external;
const Label3:         TCLabel;   code; external;

const Label4_Caption: string[3]; code; external;
const Label4:         TCLabel;   code; external;

const Label5_Caption: string[3]; code; external;
const Label5:         TCLabel;   code; external;

var   BoxRound26: TBox_Round; external;

var   BoxRound32: TBox_Round; external;

var   BoxRound33: TBox_Round; external;

var   BoxRound39: TBox_Round; external;

var   ButtonRound154_Caption: string[4];     external;
var   ButtonRound154_OnDown:  TEvent;        external;
var   ButtonRound154:         TButton_Round; external;

var   ButtonRound155_Caption: string[4];     external;
var   ButtonRound155_OnDown:  TEvent;        external;
var   ButtonRound155:         TButton_Round; external;

var   ButtonRound156_Caption: string[4];     external;
var   ButtonRound156_OnDown:  TEvent;        external;
var   ButtonRound156:         TButton_Round; external;

var   ButtonRound157_Caption: string[5];     external;
var   ButtonRound157_OnDown:  TEvent;        external;
var   ButtonRound157:         TButton_Round; external;

var   EveDial1: TEveDial; external;

const Line51: TCLine; code; external;
const ScreenOrg_Buttons_Round: array[017] of TButton_RoundPtr;  code; external;
const ScreenOrg_CLabels:       array[004] of TCLabelPtr;        code; external;
const ScreenOrg_CCircles:      array[001] of TCCirclePtr;       code; external;
const ScreenOrg_CircleButtons: array[006] of TCircleButtonPtr;  code; external;
const ScreenOrg_Boxes:         array[002] of TBoxPtr;           code; external;
const ScreenOrg_CBoxes:        array[002] of TCBoxPtr;          code; external;
const ScreenOrg_Boxes_Round:   array[008] of TBox_RoundPtr;     code; external;
const ScreenOrg_Lines:         array[001] of TLinePtr;          code; external;
const ScreenOrg_CLines:        array[003] of TCLinePtr;         code; external;
const ScreenOrg_EveDials:      array[001] of TEveDialPtr;       code; external;
const ScreenOrg_EveSliders:    array[001] of TEveSliderPtr;     code; external;


const ScreenEfx_Buttons_Round: array[023] of TButton_RoundPtr;  code; external;
const ScreenEfx_CLabels:       array[003] of TCLabelPtr;        code; external;
const ScreenEfx_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenEfx_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenEfx_Boxes_Round:   array[014] of TBox_RoundPtr;     code; external;
const ScreenEfx_CLines:        array[004] of TCLinePtr;         code; external;

var   ScreenEfx: TScreen; external;


var   Box16: TBox; external;

var   ButtonRound162_Caption: string[4];     external;
var   ButtonRound162_OnDown:  TEvent;        external;
var   ButtonRound162:         TButton_Round; external;

const Box1: TCBox; code; external;

var   ButtonRound5_Caption: string[8];     external;
var   ButtonRound5_OnDown:  TEvent;        external;
var   ButtonRound5:         TButton_Round; external;

var   ButtonRound4_Caption: string[7];     external;
var   ButtonRound4_OnDown:  TEvent;        external;
var   ButtonRound4:         TButton_Round; external;

var   ButtonRound3_Caption: string[8];     external;
var   ButtonRound3_OnDown:  TEvent;        external;
var   ButtonRound3:         TButton_Round; external;

var   ButtonRound2_Caption: string[4];     external;
var   ButtonRound2_OnDown:  TEvent;        external;
var   ButtonRound2:         TButton_Round; external;

var   ButtonRound1_Caption: string[7];     external;
var   ButtonRound1_OnDown:  TEvent;        external;
var   ButtonRound1:         TButton_Round; external;

var   ButtonRound6_Caption: string[5];     external;
var   ButtonRound6_OnDown:  TEvent;        external;
var   ButtonRound6:         TButton_Round; external;

var   ButtonRound7_Caption: string[7];     external;
var   ButtonRound7_OnDown:  TEvent;        external;
var   ButtonRound7:         TButton_Round; external;

var   ButtonRound8_Caption: string[7];     external;
var   ButtonRound8_OnDown:  TEvent;        external;
var   ButtonRound8:         TButton_Round; external;

const Box7: TCBox; code; external;

const Line11: TCLine; code; external;

const Line12: TCLine; code; external;

const Box8: TCBox; code; external;

var   BoxRound11: TBox_Round; external;

var   ButtonRound27_Caption: string[3];     external;
var   ButtonRound27_OnDown:  TEvent;        external;
var   ButtonRound27:         TButton_Round; external;

var   BoxRound5: TBox_Round; external;

var   ButtonRound9_Caption: string[8];     external;
var   ButtonRound9_OnDown:  TEvent;        external;
var   ButtonRound9:         TButton_Round; external;

var   BoxRound6: TBox_Round; external;

var   ButtonRound10_Caption: string[7];     external;
var   ButtonRound10_OnDown:  TEvent;        external;
var   ButtonRound10:         TButton_Round; external;

var   BoxRound7: TBox_Round; external;

var   ButtonRound11_Caption: string[6];     external;
var   ButtonRound11_OnDown:  TEvent;        external;
var   ButtonRound11:         TButton_Round; external;

var   BoxRound9: TBox_Round; external;

var   ButtonRound13_Caption: string[4];     external;
var   ButtonRound13_OnDown:  TEvent;        external;
var   ButtonRound13:         TButton_Round; external;

var   BoxRound8: TBox_Round; external;

var   ButtonRound12_Caption: string[4];     external;
var   ButtonRound12_OnDown:  TEvent;        external;
var   ButtonRound12:         TButton_Round; external;

var   BoxRound10: TBox_Round; external;

var   ButtonRound26_Caption: string[4];     external;
var   ButtonRound26_OnDown:  TEvent;        external;
var   ButtonRound26:         TButton_Round; external;

var   BoxRound12: TBox_Round; external;

var   ButtonRound40_Caption: string[5];     external;
var   ButtonRound40_OnDown:  TEvent;        external;
var   ButtonRound40:         TButton_Round; external;

const Label10_Caption: string[19]; code; external;
const Label10:         TCLabel;    code; external;

var   BoxRound28: TBox_Round; external;

var   ButtonRound72_Caption: string[5];     external;
var   ButtonRound72_OnDown:  TEvent;        external;
var   ButtonRound72:         TButton_Round; external;

var   BoxRound29: TBox_Round; external;

var   ButtonRound73_Caption: string[6];     external;
var   ButtonRound73_OnDown:  TEvent;        external;
var   ButtonRound73:         TButton_Round; external;

const Label7_Caption: string[19]; code; external;
const Label7:         TCLabel;    code; external;

var   BoxRound16: TBox_Round; external;

var   ButtonRound17_Caption: string[7];     external;
var   ButtonRound17_OnDown:  TEvent;        external;
var   ButtonRound17:         TButton_Round; external;

var   BoxRound17: TBox_Round; external;

var   ButtonRound18_Caption: string[6];     external;
var   ButtonRound18_OnDown:  TEvent;        external;
var   ButtonRound18:         TButton_Round; external;

const Label9_Caption: string[19]; code; external;
const Label9:         TCLabel;    code; external;

var   BoxRound18: TBox_Round; external;

var   BoxRound19: TBox_Round; external;

var   ButtonRound48_Caption: string[9];     external;
var   ButtonRound48_OnDown:  TEvent;        external;
var   ButtonRound48:         TButton_Round; external;

var   ButtonRound49_Caption: string[9];     external;
var   ButtonRound49_OnDown:  TEvent;        external;
var   ButtonRound49:         TButton_Round; external;

const Line52: TCLine; code; external;

const Line1: TCLine; code; external;
const ScreenEfx_Buttons_Round: array[023] of TButton_RoundPtr;  code; external;
const ScreenEfx_CLabels:       array[003] of TCLabelPtr;        code; external;
const ScreenEfx_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenEfx_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenEfx_Boxes_Round:   array[014] of TBox_RoundPtr;     code; external;
const ScreenEfx_CLines:        array[004] of TCLinePtr;         code; external;


const ScreenOpt_Buttons_Round: array[014] of TButton_RoundPtr;  code; external;
const ScreenOpt_CLabels:       array[002] of TCLabelPtr;        code; external;
const ScreenOpt_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenOpt_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenOpt_Boxes_Round:   array[005] of TBox_RoundPtr;     code; external;
const ScreenOpt_CLines:        array[004] of TCLinePtr;         code; external;

var   ScreenOpt: TScreen; external;


var   Box17: TBox; external;

var   ButtonRound163_Caption: string[7];     external;
var   ButtonRound163_OnDown:  TEvent;        external;
var   ButtonRound163:         TButton_Round; external;

var   ButtonRound45_Caption: string[4];     external;
var   ButtonRound45_OnDown:  TEvent;        external;
var   ButtonRound45:         TButton_Round; external;

var   ButtonRound44_Caption: string[8];     external;
var   ButtonRound44_OnDown:  TEvent;        external;
var   ButtonRound44:         TButton_Round; external;

var   ButtonRound43_Caption: string[7];     external;
var   ButtonRound43_OnDown:  TEvent;        external;
var   ButtonRound43:         TButton_Round; external;

var   ButtonRound42_Caption: string[8];     external;
var   ButtonRound42_OnDown:  TEvent;        external;
var   ButtonRound42:         TButton_Round; external;

var   ButtonRound41_Caption: string[4];     external;
var   ButtonRound41_OnDown:  TEvent;        external;
var   ButtonRound41:         TButton_Round; external;

const Box9: TCBox; code; external;

var   ButtonRound46_Caption: string[5];     external;
var   ButtonRound46_OnDown:  TEvent;        external;
var   ButtonRound46:         TButton_Round; external;

var   ButtonRound47_Caption: string[7];     external;
var   ButtonRound47_OnDown:  TEvent;        external;
var   ButtonRound47:         TButton_Round; external;

var   ButtonRound53_Caption: string[7];     external;
var   ButtonRound53_OnDown:  TEvent;        external;
var   ButtonRound53:         TButton_Round; external;

const Box14: TCBox; code; external;

const Box13: TCBox; code; external;

const Line14: TCLine; code; external;

const Line15: TCLine; code; external;

var   BoxRound1: TBox_Round; external;

var   ButtonRound14_Caption: string[8];     external;
var   ButtonRound14_OnDown:  TEvent;        external;
var   ButtonRound14:         TButton_Round; external;

const Label6_Caption: string[7]; code; external;
const Label6:         TCLabel;   code; external;

var   BoxRound14: TBox_Round; external;

var   ButtonRound15_Caption: string[8];     external;
var   ButtonRound15_OnDown:  TEvent;        external;
var   ButtonRound15:         TButton_Round; external;

var   BoxRound15: TBox_Round; external;

var   ButtonRound16_Caption: string[8];     external;
var   ButtonRound16_OnDown:  TEvent;        external;
var   ButtonRound16:         TButton_Round; external;

const Label8_Caption: string[12]; code; external;
const Label8:         TCLabel;    code; external;

var   BoxRound30: TBox_Round; external;

var   ButtonRound74_Caption: string[7];     external;
var   ButtonRound74_OnDown:  TEvent;        external;
var   ButtonRound74:         TButton_Round; external;

var   BoxRound31: TBox_Round; external;

var   ButtonRound75_Caption: string[8];     external;
var   ButtonRound75_OnDown:  TEvent;        external;
var   ButtonRound75:         TButton_Round; external;

const Line13: TCLine; code; external;

const Line53: TCLine; code; external;
const ScreenOpt_Buttons_Round: array[014] of TButton_RoundPtr;  code; external;
const ScreenOpt_CLabels:       array[002] of TCLabelPtr;        code; external;
const ScreenOpt_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenOpt_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenOpt_Boxes_Round:   array[005] of TBox_RoundPtr;     code; external;
const ScreenOpt_CLines:        array[004] of TCLinePtr;         code; external;


const ScreenDBupper_Buttons_Round: array[018] of TButton_RoundPtr;  code; external;
const ScreenDBupper_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenDBupper_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenDBupper_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenDBupper_Boxes_Round:   array[007] of TBox_RoundPtr;     code; external;
const ScreenDBupper_Lines:         array[001] of TLinePtr;          code; external;
const ScreenDBupper_CLines:        array[003] of TCLinePtr;         code; external;
const ScreenDBupper_EveScrollBars: array[012] of TEveScrollbarPtr;  code; external;

var   ScreenDBupper: TScreen; external;


var   Box23: TBox; external;

var   ButtonRound164_Caption: string[7];     external;
var   ButtonRound164_OnDown:  TEvent;        external;
var   ButtonRound164:         TButton_Round; external;

var   ButtonRound84_Caption: string[4];     external;
var   ButtonRound84_OnDown:  TEvent;        external;
var   ButtonRound84:         TButton_Round; external;

var   ButtonRound83_Caption: string[8];     external;
var   ButtonRound83_OnDown:  TEvent;        external;
var   ButtonRound83:         TButton_Round; external;

var   ButtonRound82_Caption: string[7];     external;
var   ButtonRound82_OnDown:  TEvent;        external;
var   ButtonRound82:         TButton_Round; external;

var   ButtonRound81_Caption: string[8];     external;
var   ButtonRound81_OnDown:  TEvent;        external;
var   ButtonRound81:         TButton_Round; external;

var   ButtonRound52_Caption: string[4];     external;
var   ButtonRound52_OnDown:  TEvent;        external;
var   ButtonRound52:         TButton_Round; external;

const Box24: TCBox; code; external;

var   ButtonRound76_Caption: string[4];     external;
var   ButtonRound76_OnDown:  TEvent;        external;
var   ButtonRound76:         TButton_Round; external;

var   ButtonRound77_Caption: string[5];     external;
var   ButtonRound77_OnDown:  TEvent;        external;
var   ButtonRound77:         TButton_Round; external;

var   ButtonRound78_Caption: string[5];     external;
var   ButtonRound78_OnDown:  TEvent;        external;
var   ButtonRound78:         TButton_Round; external;

var   ButtonRound79_Caption: string[5];     external;
var   ButtonRound79_OnDown:  TEvent;        external;
var   ButtonRound79:         TButton_Round; external;

var   ButtonRound80_Caption: string[8];     external;
var   ButtonRound80_OnDown:  TEvent;        external;
var   ButtonRound80:         TButton_Round; external;

const Box25: TCBox; code; external;

var   Line19: TLine; external;

var   EveScrollBar17_OnPress: TEvent;        external;
var   EveScrollBar17:         TEveScrollbar; external;

var   EveScrollBar18_OnPress: TEvent;        external;
var   EveScrollBar18:         TEveScrollbar; external;

var   EveScrollBar19_OnPress: TEvent;        external;
var   EveScrollBar19:         TEveScrollbar; external;

var   EveScrollBar20_OnPress: TEvent;        external;
var   EveScrollBar20:         TEveScrollbar; external;

var   EveScrollBar21_OnPress: TEvent;        external;
var   EveScrollBar21:         TEveScrollbar; external;

var   EveScrollBar22_OnPress: TEvent;        external;
var   EveScrollBar22:         TEveScrollbar; external;

var   EveScrollBar23_OnPress: TEvent;        external;
var   EveScrollBar23:         TEveScrollbar; external;

var   EveScrollBar24_OnPress: TEvent;        external;
var   EveScrollBar24:         TEveScrollbar; external;

var   EveScrollBar29_OnPress: TEvent;        external;
var   EveScrollBar29:         TEveScrollbar; external;

var   EveScrollBar30_OnPress: TEvent;        external;
var   EveScrollBar30:         TEveScrollbar; external;

var   EveScrollBar31_OnPress: TEvent;        external;
var   EveScrollBar31:         TEveScrollbar; external;

var   EveScrollBar32_OnPress: TEvent;        external;
var   EveScrollBar32:         TEveScrollbar; external;

const Box26: TCBox; code; external;

const Line20: TCLine; code; external;

const Label12_Caption: string[5]; code; external;
const Label12:         TCLabel;   code; external;

var   BoxRound34: TBox_Round; external;

var   BoxRound35: TBox_Round; external;

var   BoxRound36: TBox_Round; external;

var   BoxRound37: TBox_Round; external;

var   ButtonRound85_Caption: string[4];     external;
var   ButtonRound85_OnDown:  TEvent;        external;
var   ButtonRound85:         TButton_Round; external;

var   ButtonRound86_Caption: string[4];     external;
var   ButtonRound86_OnDown:  TEvent;        external;
var   ButtonRound86:         TButton_Round; external;

var   ButtonRound87_Caption: string[4];     external;
var   ButtonRound87_OnDown:  TEvent;        external;
var   ButtonRound87:         TButton_Round; external;

var   ButtonRound88_Caption: string[5];     external;
var   ButtonRound88_OnDown:  TEvent;        external;
var   ButtonRound88:         TButton_Round; external;

var   BoxRound38_OnDown: TEvent;     external;
var   BoxRound38:        TBox_Round; external;

var   ButtonRound89_Caption: string[7];     external;
var   ButtonRound89_OnDown:  TEvent;        external;
var   ButtonRound89:         TButton_Round; external;

var   BoxRound20: TBox_Round; external;

var   ButtonRound50_Caption: string[9];     external;
var   ButtonRound50_OnDown:  TEvent;        external;
var   ButtonRound50:         TButton_Round; external;

var   BoxRound21: TBox_Round; external;

var   ButtonRound51_Caption: string[9];     external;
var   ButtonRound51_OnDown:  TEvent;        external;
var   ButtonRound51:         TButton_Round; external;

const Line22: TCLine; code; external;

const Line21: TCLine; code; external;
const ScreenDBupper_Buttons_Round: array[018] of TButton_RoundPtr;  code; external;
const ScreenDBupper_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenDBupper_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenDBupper_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenDBupper_Boxes_Round:   array[007] of TBox_RoundPtr;     code; external;
const ScreenDBupper_Lines:         array[001] of TLinePtr;          code; external;
const ScreenDBupper_CLines:        array[003] of TCLinePtr;         code; external;
const ScreenDBupper_EveScrollBars: array[012] of TEveScrollbarPtr;  code; external;


const ScreenDBenvelope_Buttons_Round: array[014] of TButton_RoundPtr;  code; external;
const ScreenDBenvelope_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenDBenvelope_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenDBenvelope_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenDBenvelope_Boxes_Round:   array[003] of TBox_RoundPtr;     code; external;
const ScreenDBenvelope_CLines:        array[004] of TCLinePtr;         code; external;
const ScreenDBenvelope_CheckBoxes:    array[012] of TCheckBoxPtr;      code; external;
const ScreenDBenvelope_EveScrollBars: array[012] of TEveScrollbarPtr;  code; external;

var   ScreenDBenvelope: TScreen; external;


var   Box27: TBox; external;

var   ButtonRound165_Caption: string[4];     external;
var   ButtonRound165_OnDown:  TEvent;        external;
var   ButtonRound165:         TButton_Round; external;

var   ButtonRound100_Caption: string[8];     external;
var   ButtonRound100_OnDown:  TEvent;        external;
var   ButtonRound100:         TButton_Round; external;

var   ButtonRound99_Caption: string[7];     external;
var   ButtonRound99_OnDown:  TEvent;        external;
var   ButtonRound99:         TButton_Round; external;

var   ButtonRound98_Caption: string[8];     external;
var   ButtonRound98_OnDown:  TEvent;        external;
var   ButtonRound98:         TButton_Round; external;

var   ButtonRound97_Caption: string[4];     external;
var   ButtonRound97_OnDown:  TEvent;        external;
var   ButtonRound97:         TButton_Round; external;

var   ButtonRound91_Caption: string[7];     external;
var   ButtonRound91_OnDown:  TEvent;        external;
var   ButtonRound91:         TButton_Round; external;

const Box28: TCBox; code; external;

var   ButtonRound92_Caption: string[4];     external;
var   ButtonRound92_OnDown:  TEvent;        external;
var   ButtonRound92:         TButton_Round; external;

var   ButtonRound93_Caption: string[5];     external;
var   ButtonRound93_OnDown:  TEvent;        external;
var   ButtonRound93:         TButton_Round; external;

var   ButtonRound94_Caption: string[5];     external;
var   ButtonRound94_OnDown:  TEvent;        external;
var   ButtonRound94:         TButton_Round; external;

var   ButtonRound95_Caption: string[5];     external;
var   ButtonRound95_OnDown:  TEvent;        external;
var   ButtonRound95:         TButton_Round; external;

var   ButtonRound96_Caption: string[8];     external;
var   ButtonRound96_OnDown:  TEvent;        external;
var   ButtonRound96:         TButton_Round; external;

const Box29: TCBox; code; external;

const Line23: TCLine; code; external;

var   EveScrollBar42_OnPress: TEvent;        external;
var   EveScrollBar42:         TEveScrollbar; external;

var   EveScrollBar43_OnPress: TEvent;        external;
var   EveScrollBar43:         TEveScrollbar; external;

var   EveScrollBar44_OnPress: TEvent;        external;
var   EveScrollBar44:         TEveScrollbar; external;

var   EveScrollBar45_OnPress: TEvent;        external;
var   EveScrollBar45:         TEveScrollbar; external;

var   EveScrollBar46_OnPress: TEvent;        external;
var   EveScrollBar46:         TEveScrollbar; external;

var   EveScrollBar47_OnPress: TEvent;        external;
var   EveScrollBar47:         TEveScrollbar; external;

var   EveScrollBar48_OnPress: TEvent;        external;
var   EveScrollBar48:         TEveScrollbar; external;

var   EveScrollBar49_OnPress: TEvent;        external;
var   EveScrollBar49:         TEveScrollbar; external;

var   EveScrollBar50_OnPress: TEvent;        external;
var   EveScrollBar50:         TEveScrollbar; external;

var   EveScrollBar51_OnPress: TEvent;        external;
var   EveScrollBar51:         TEveScrollbar; external;

var   EveScrollBar52_OnPress: TEvent;        external;
var   EveScrollBar52:         TEveScrollbar; external;

var   EveScrollBar53_OnPress: TEvent;        external;
var   EveScrollBar53:         TEveScrollbar; external;

const Line24: TCLine; code; external;

const Label22_Caption: string[14]; code; external;
const Label22:         TCLabel;    code; external;

var   BoxRound46_OnDown: TEvent;     external;
var   BoxRound46:        TBox_Round; external;

var   ButtonRound105_Caption: string[6];     external;
var   ButtonRound105_OnDown:  TEvent;        external;
var   ButtonRound105:         TButton_Round; external;

var   CheckBox1_Caption: string[1]; external;
var   CheckBox1_OnDown:  TEvent;    external;
var   CheckBox1:         TCheckBox; external;

var   CheckBox2_Caption: string[1]; external;
var   CheckBox2_OnDown:  TEvent;    external;
var   CheckBox2:         TCheckBox; external;

var   CheckBox3_Caption: string[1]; external;
var   CheckBox3_OnDown:  TEvent;    external;
var   CheckBox3:         TCheckBox; external;

var   CheckBox4_Caption: string[1]; external;
var   CheckBox4_OnDown:  TEvent;    external;
var   CheckBox4:         TCheckBox; external;

var   CheckBox5_Caption: string[1]; external;
var   CheckBox5_OnDown:  TEvent;    external;
var   CheckBox5:         TCheckBox; external;

var   CheckBox6_Caption: string[1]; external;
var   CheckBox6_OnDown:  TEvent;    external;
var   CheckBox6:         TCheckBox; external;

var   CheckBox7_Caption: string[1]; external;
var   CheckBox7_OnDown:  TEvent;    external;
var   CheckBox7:         TCheckBox; external;

var   CheckBox8_Caption: string[1]; external;
var   CheckBox8_OnDown:  TEvent;    external;
var   CheckBox8:         TCheckBox; external;

var   CheckBox9_Caption: string[1]; external;
var   CheckBox9_OnDown:  TEvent;    external;
var   CheckBox9:         TCheckBox; external;

var   CheckBox10_Caption: string[1]; external;
var   CheckBox10_OnDown:  TEvent;    external;
var   CheckBox10:         TCheckBox; external;

var   CheckBox11_Caption: string[1]; external;
var   CheckBox11_OnDown:  TEvent;    external;
var   CheckBox11:         TCheckBox; external;

var   CheckBox12_Caption: string[1]; external;
var   CheckBox12_OnDown:  TEvent;    external;
var   CheckBox12:         TCheckBox; external;

var   BoxRound3: TBox_Round; external;

var   ButtonRound152_Caption: string[9];     external;
var   ButtonRound152_OnDown:  TEvent;        external;
var   ButtonRound152:         TButton_Round; external;

var   BoxRound25: TBox_Round; external;

var   ButtonRound153_Caption: string[9];     external;
var   ButtonRound153_OnDown:  TEvent;        external;
var   ButtonRound153:         TButton_Round; external;

const Box30: TCBox; code; external;

const Line25: TCLine; code; external;

const Line26: TCLine; code; external;
const ScreenDBenvelope_Buttons_Round: array[014] of TButton_RoundPtr;  code; external;
const ScreenDBenvelope_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenDBenvelope_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenDBenvelope_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenDBenvelope_Boxes_Round:   array[003] of TBox_RoundPtr;     code; external;
const ScreenDBenvelope_CLines:        array[004] of TCLinePtr;         code; external;
const ScreenDBenvelope_CheckBoxes:    array[012] of TCheckBoxPtr;      code; external;
const ScreenDBenvelope_EveScrollBars: array[012] of TEveScrollbarPtr;  code; external;


const ScreenDBadsr_Buttons_Round: array[011] of TButton_RoundPtr;  code; external;
const ScreenDBadsr_Labels:        array[010] of TLabelPtr;         code; external;
const ScreenDBadsr_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenDBadsr_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenDBadsr_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenDBadsr_CLines:        array[004] of TCLinePtr;         code; external;
const ScreenDBadsr_EveScrollBars: array[010] of TEveScrollbarPtr;  code; external;

var   ScreenDBadsr: TScreen; external;


var   Box31: TBox; external;

var   ButtonRound166_Caption: string[7];     external;
var   ButtonRound166_OnDown:  TEvent;        external;
var   ButtonRound166:         TButton_Round; external;

var   ButtonRound116_Caption: string[4];     external;
var   ButtonRound116_OnDown:  TEvent;        external;
var   ButtonRound116:         TButton_Round; external;

var   ButtonRound115_Caption: string[8];     external;
var   ButtonRound115_OnDown:  TEvent;        external;
var   ButtonRound115:         TButton_Round; external;

var   ButtonRound114_Caption: string[7];     external;
var   ButtonRound114_OnDown:  TEvent;        external;
var   ButtonRound114:         TButton_Round; external;

var   ButtonRound113_Caption: string[8];     external;
var   ButtonRound113_OnDown:  TEvent;        external;
var   ButtonRound113:         TButton_Round; external;

var   ButtonRound107_Caption: string[4];     external;
var   ButtonRound107_OnDown:  TEvent;        external;
var   ButtonRound107:         TButton_Round; external;

const Box32: TCBox; code; external;

var   ButtonRound108_Caption: string[4];     external;
var   ButtonRound108_OnDown:  TEvent;        external;
var   ButtonRound108:         TButton_Round; external;

var   ButtonRound109_Caption: string[5];     external;
var   ButtonRound109_OnDown:  TEvent;        external;
var   ButtonRound109:         TButton_Round; external;

var   ButtonRound110_Caption: string[5];     external;
var   ButtonRound110_OnDown:  TEvent;        external;
var   ButtonRound110:         TButton_Round; external;

var   ButtonRound111_Caption: string[5];     external;
var   ButtonRound111_OnDown:  TEvent;        external;
var   ButtonRound111:         TButton_Round; external;

var   ButtonRound112_Caption: string[8];     external;
var   ButtonRound112_OnDown:  TEvent;        external;
var   ButtonRound112:         TButton_Round; external;

const Box33: TCBox; code; external;

const Line27: TCLine; code; external;

const Line28: TCLine; code; external;

const Label32_Caption: string[16]; code; external;
const Label32:         TCLabel;    code; external;

var   EveScrollBar76_OnPress: TEvent;        external;
var   EveScrollBar76:         TEveScrollbar; external;

var   Label33_Caption: string[13]; external;
var   Label33:         TLabel;     external;

var   EveScrollBar77_OnPress: TEvent;        external;
var   EveScrollBar77:         TEveScrollbar; external;

var   Label34_Caption: string[13]; external;
var   Label34:         TLabel;     external;

var   EveScrollBar78_OnPress: TEvent;        external;
var   EveScrollBar78:         TEveScrollbar; external;

var   Label35_Caption: string[11]; external;
var   Label35:         TLabel;     external;

var   EveScrollBar79_OnPress: TEvent;        external;
var   EveScrollBar79:         TEveScrollbar; external;

var   Label36_Caption: string[12]; external;
var   Label36:         TLabel;     external;

var   EveScrollBar80_OnPress: TEvent;        external;
var   EveScrollBar80:         TEveScrollbar; external;

var   Label37_Caption: string[13]; external;
var   Label37:         TLabel;     external;

var   EveScrollBar81_OnPress: TEvent;        external;
var   EveScrollBar81:         TEveScrollbar; external;

var   Label38_Caption: string[13]; external;
var   Label38:         TLabel;     external;

var   EveScrollBar82_OnPress: TEvent;        external;
var   EveScrollBar82:         TEveScrollbar; external;

var   Label39_Caption: string[11]; external;
var   Label39:         TLabel;     external;

var   EveScrollBar83_OnPress: TEvent;        external;
var   EveScrollBar83:         TEveScrollbar; external;

var   Label40_Caption: string[12]; external;
var   Label40:         TLabel;     external;

var   EveScrollBar1_OnPress: TEvent;        external;
var   EveScrollBar1:         TEveScrollbar; external;

var   Label11_Caption: string[15]; external;
var   Label11:         TLabel;     external;

var   EveScrollBar2_OnPress: TEvent;        external;
var   EveScrollBar2:         TEveScrollbar; external;

var   Label13_Caption: string[15]; external;
var   Label13:         TLabel;     external;

const Box34: TCBox; code; external;

const Line29: TCLine; code; external;

const Line30: TCLine; code; external;
const ScreenDBadsr_Buttons_Round: array[011] of TButton_RoundPtr;  code; external;
const ScreenDBadsr_Labels:        array[010] of TLabelPtr;         code; external;
const ScreenDBadsr_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenDBadsr_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenDBadsr_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenDBadsr_CLines:        array[004] of TCLinePtr;         code; external;
const ScreenDBadsr_EveScrollBars: array[010] of TEveScrollbarPtr;  code; external;


const ScreenDBlower_Buttons_Round: array[012] of TButton_RoundPtr;  code; external;
const ScreenDBlower_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenDBlower_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenDBlower_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenDBlower_Boxes_Round:   array[001] of TBox_RoundPtr;     code; external;
const ScreenDBlower_CLines:        array[004] of TCLinePtr;         code; external;
const ScreenDBlower_CheckBoxes:    array[012] of TCheckBoxPtr;      code; external;
const ScreenDBlower_EveScrollBars: array[012] of TEveScrollbarPtr;  code; external;

var   ScreenDBlower: TScreen; external;


var   Box35: TBox; external;

var   ButtonRound167_Caption: string[7];     external;
var   ButtonRound167_OnDown:  TEvent;        external;
var   ButtonRound167:         TButton_Round; external;

var   ButtonRound132_Caption: string[4];     external;
var   ButtonRound132_OnDown:  TEvent;        external;
var   ButtonRound132:         TButton_Round; external;

var   ButtonRound131_Caption: string[8];     external;
var   ButtonRound131_OnDown:  TEvent;        external;
var   ButtonRound131:         TButton_Round; external;

var   ButtonRound130_Caption: string[7];     external;
var   ButtonRound130_OnDown:  TEvent;        external;
var   ButtonRound130:         TButton_Round; external;

var   ButtonRound129_Caption: string[8];     external;
var   ButtonRound129_OnDown:  TEvent;        external;
var   ButtonRound129:         TButton_Round; external;

var   ButtonRound123_Caption: string[4];     external;
var   ButtonRound123_OnDown:  TEvent;        external;
var   ButtonRound123:         TButton_Round; external;

const Box36: TCBox; code; external;

var   ButtonRound124_Caption: string[4];     external;
var   ButtonRound124_OnDown:  TEvent;        external;
var   ButtonRound124:         TButton_Round; external;

var   ButtonRound125_Caption: string[5];     external;
var   ButtonRound125_OnDown:  TEvent;        external;
var   ButtonRound125:         TButton_Round; external;

var   ButtonRound126_Caption: string[5];     external;
var   ButtonRound126_OnDown:  TEvent;        external;
var   ButtonRound126:         TButton_Round; external;

var   ButtonRound127_Caption: string[5];     external;
var   ButtonRound127_OnDown:  TEvent;        external;
var   ButtonRound127:         TButton_Round; external;

var   ButtonRound128_Caption: string[8];     external;
var   ButtonRound128_OnDown:  TEvent;        external;
var   ButtonRound128:         TButton_Round; external;

const Box37: TCBox; code; external;

const Line31: TCLine; code; external;

var   EveScrollBar84_OnPress: TEvent;        external;
var   EveScrollBar84:         TEveScrollbar; external;

var   EveScrollBar85_OnPress: TEvent;        external;
var   EveScrollBar85:         TEveScrollbar; external;

var   EveScrollBar86_OnPress: TEvent;        external;
var   EveScrollBar86:         TEveScrollbar; external;

var   EveScrollBar87_OnPress: TEvent;        external;
var   EveScrollBar87:         TEveScrollbar; external;

var   EveScrollBar88_OnPress: TEvent;        external;
var   EveScrollBar88:         TEveScrollbar; external;

var   EveScrollBar89_OnPress: TEvent;        external;
var   EveScrollBar89:         TEveScrollbar; external;

var   EveScrollBar90_OnPress: TEvent;        external;
var   EveScrollBar90:         TEveScrollbar; external;

var   EveScrollBar91_OnPress: TEvent;        external;
var   EveScrollBar91:         TEveScrollbar; external;

var   EveScrollBar92_OnPress: TEvent;        external;
var   EveScrollBar92:         TEveScrollbar; external;

var   EveScrollBar93_OnPress: TEvent;        external;
var   EveScrollBar93:         TEveScrollbar; external;

var   EveScrollBar94_OnPress: TEvent;        external;
var   EveScrollBar94:         TEveScrollbar; external;

var   EveScrollBar95_OnPress: TEvent;        external;
var   EveScrollBar95:         TEveScrollbar; external;

const Box38: TCBox; code; external;

const Line32: TCLine; code; external;

const Label42_Caption: string[5]; code; external;
const Label42:         TCLabel;   code; external;

var   BoxRound63: TBox_Round; external;

var   ButtonRound138_Caption: string[7];     external;
var   ButtonRound138_OnDown:  TEvent;        external;
var   ButtonRound138:         TButton_Round; external;

var   CheckBox13_Caption: string[1]; external;
var   CheckBox13_OnDown:  TEvent;    external;
var   CheckBox13:         TCheckBox; external;

var   CheckBox14_Caption: string[1]; external;
var   CheckBox14_OnDown:  TEvent;    external;
var   CheckBox14:         TCheckBox; external;

var   CheckBox15_Caption: string[1]; external;
var   CheckBox15_OnDown:  TEvent;    external;
var   CheckBox15:         TCheckBox; external;

var   CheckBox16_Caption: string[1]; external;
var   CheckBox16_OnDown:  TEvent;    external;
var   CheckBox16:         TCheckBox; external;

var   CheckBox17_Caption: string[1]; external;
var   CheckBox17_OnDown:  TEvent;    external;
var   CheckBox17:         TCheckBox; external;

var   CheckBox18_Caption: string[1]; external;
var   CheckBox18_OnDown:  TEvent;    external;
var   CheckBox18:         TCheckBox; external;

var   CheckBox19_Caption: string[1]; external;
var   CheckBox19_OnDown:  TEvent;    external;
var   CheckBox19:         TCheckBox; external;

var   CheckBox20_Caption: string[1]; external;
var   CheckBox20_OnDown:  TEvent;    external;
var   CheckBox20:         TCheckBox; external;

var   CheckBox21_Caption: string[1]; external;
var   CheckBox21_OnDown:  TEvent;    external;
var   CheckBox21:         TCheckBox; external;

var   CheckBox22_Caption: string[1]; external;
var   CheckBox22_OnDown:  TEvent;    external;
var   CheckBox22:         TCheckBox; external;

var   CheckBox23_Caption: string[1]; external;
var   CheckBox23_OnDown:  TEvent;    external;
var   CheckBox23:         TCheckBox; external;

var   CheckBox24_Caption: string[1]; external;
var   CheckBox24_OnDown:  TEvent;    external;
var   CheckBox24:         TCheckBox; external;

const Line33: TCLine; code; external;

const Line34: TCLine; code; external;
const ScreenDBlower_Buttons_Round: array[012] of TButton_RoundPtr;  code; external;
const ScreenDBlower_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenDBlower_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenDBlower_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenDBlower_Boxes_Round:   array[001] of TBox_RoundPtr;     code; external;
const ScreenDBlower_CLines:        array[004] of TCLinePtr;         code; external;
const ScreenDBlower_CheckBoxes:    array[012] of TCheckBoxPtr;      code; external;
const ScreenDBlower_EveScrollBars: array[012] of TEveScrollbarPtr;  code; external;


const ScreenDBpedal_Buttons_Round: array[012] of TButton_RoundPtr;  code; external;
const ScreenDBpedal_Labels:        array[005] of TLabelPtr;         code; external;
const ScreenDBpedal_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenDBpedal_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenDBpedal_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenDBpedal_Boxes_Round:   array[001] of TBox_RoundPtr;     code; external;
const ScreenDBpedal_CLines:        array[004] of TCLinePtr;         code; external;
const ScreenDBpedal_EveScrollBars: array[009] of TEveScrollbarPtr;  code; external;

var   ScreenDBpedal: TScreen; external;


var   Box39: TBox; external;

var   ButtonRound168_Caption: string[7];     external;
var   ButtonRound168_OnDown:  TEvent;        external;
var   ButtonRound168:         TButton_Round; external;

var   ButtonRound148_Caption: string[4];     external;
var   ButtonRound148_OnDown:  TEvent;        external;
var   ButtonRound148:         TButton_Round; external;

var   ButtonRound147_Caption: string[8];     external;
var   ButtonRound147_OnDown:  TEvent;        external;
var   ButtonRound147:         TButton_Round; external;

var   ButtonRound146_Caption: string[7];     external;
var   ButtonRound146_OnDown:  TEvent;        external;
var   ButtonRound146:         TButton_Round; external;

var   ButtonRound145_Caption: string[8];     external;
var   ButtonRound145_OnDown:  TEvent;        external;
var   ButtonRound145:         TButton_Round; external;

var   ButtonRound139_Caption: string[4];     external;
var   ButtonRound139_OnDown:  TEvent;        external;
var   ButtonRound139:         TButton_Round; external;

const Box40: TCBox; code; external;

var   ButtonRound140_Caption: string[4];     external;
var   ButtonRound140_OnDown:  TEvent;        external;
var   ButtonRound140:         TButton_Round; external;

var   ButtonRound141_Caption: string[5];     external;
var   ButtonRound141_OnDown:  TEvent;        external;
var   ButtonRound141:         TButton_Round; external;

var   ButtonRound142_Caption: string[5];     external;
var   ButtonRound142_OnDown:  TEvent;        external;
var   ButtonRound142:         TButton_Round; external;

var   ButtonRound143_Caption: string[5];     external;
var   ButtonRound143_OnDown:  TEvent;        external;
var   ButtonRound143:         TButton_Round; external;

var   ButtonRound144_Caption: string[8];     external;
var   ButtonRound144_OnDown:  TEvent;        external;
var   ButtonRound144:         TButton_Round; external;

const Box41: TCBox; code; external;

const Line35: TCLine; code; external;

var   EveScrollBar105_OnPress: TEvent;        external;
var   EveScrollBar105:         TEveScrollbar; external;

var   EveScrollBar106_OnPress: TEvent;        external;
var   EveScrollBar106:         TEveScrollbar; external;

var   EveScrollBar107_OnPress: TEvent;        external;
var   EveScrollBar107:         TEveScrollbar; external;

var   EveScrollBar108_OnPress: TEvent;        external;
var   EveScrollBar108:         TEveScrollbar; external;

const Box42: TCBox; code; external;

const Line36: TCLine; code; external;

const Label52_Caption: string[5]; code; external;
const Label52:         TCLabel;   code; external;

var   EveScrollBar56_OnPress: TEvent;        external;
var   EveScrollBar56:         TEveScrollbar; external;

var   Label74_Caption: string[13]; external;
var   Label74:         TLabel;     external;

var   EveScrollBar59_OnPress: TEvent;        external;
var   EveScrollBar59:         TEveScrollbar; external;

var   Label75_Caption: string[13]; external;
var   Label75:         TLabel;     external;

var   EveScrollBar68_OnPress: TEvent;        external;
var   EveScrollBar68:         TEveScrollbar; external;

var   Label76_Caption: string[11]; external;
var   Label76:         TLabel;     external;

var   EveScrollBar69_OnPress: TEvent;        external;
var   EveScrollBar69:         TEveScrollbar; external;

var   Label77_Caption: string[12]; external;
var   Label77:         TLabel;     external;

var   EveScrollBar70_OnPress: TEvent;        external;
var   EveScrollBar70:         TEveScrollbar; external;

var   Label78_Caption: string[15]; external;
var   Label78:         TLabel;     external;

var   BoxRound23_OnDown: TEvent;     external;
var   BoxRound23:        TBox_Round; external;

var   ButtonRound151_Caption: string[6];     external;
var   ButtonRound151_OnDown:  TEvent;        external;
var   ButtonRound151:         TButton_Round; external;

const Line38: TCLine; code; external;

const Line37: TCLine; code; external;
const ScreenDBpedal_Buttons_Round: array[012] of TButton_RoundPtr;  code; external;
const ScreenDBpedal_Labels:        array[005] of TLabelPtr;         code; external;
const ScreenDBpedal_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenDBpedal_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenDBpedal_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenDBpedal_Boxes_Round:   array[001] of TBox_RoundPtr;     code; external;
const ScreenDBpedal_CLines:        array[004] of TCLinePtr;         code; external;
const ScreenDBpedal_EveScrollBars: array[009] of TEveScrollbarPtr;  code; external;


const ScreenGMsynthUpr_Buttons_Round: array[009] of TButton_RoundPtr;  code; external;
const ScreenGMsynthUpr_Labels:        array[007] of TLabelPtr;         code; external;
const ScreenGMsynthUpr_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenGMsynthUpr_CircleButtons: array[004] of TCircleButtonPtr;  code; external;
const ScreenGMsynthUpr_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenGMsynthUpr_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenGMsynthUpr_Lines:         array[001] of TLinePtr;          code; external;
const ScreenGMsynthUpr_CLines:        array[003] of TCLinePtr;         code; external;
const ScreenGMsynthUpr_EveScrollBars: array[007] of TEveScrollbarPtr;  code; external;
const ScreenGMsynthUpr_EveNumbers:    array[002] of TEveNumberPtr;     code; external;

var   ScreenGMsynthUpr: TScreen; external;


var   Box47: TBox; external;

var   ButtonRound169_Caption: string[7];     external;
var   ButtonRound169_OnDown:  TEvent;        external;
var   ButtonRound169:         TButton_Round; external;

var   ButtonRound118_Caption: string[4];     external;
var   ButtonRound118_OnDown:  TEvent;        external;
var   ButtonRound118:         TButton_Round; external;

var   ButtonRound117_Caption: string[8];     external;
var   ButtonRound117_OnDown:  TEvent;        external;
var   ButtonRound117:         TButton_Round; external;

var   ButtonRound106_Caption: string[7];     external;
var   ButtonRound106_OnDown:  TEvent;        external;
var   ButtonRound106:         TButton_Round; external;

var   ButtonRound104_Caption: string[8];     external;
var   ButtonRound104_OnDown:  TEvent;        external;
var   ButtonRound104:         TButton_Round; external;

var   ButtonRound103_Caption: string[4];     external;
var   ButtonRound103_OnDown:  TEvent;        external;
var   ButtonRound103:         TButton_Round; external;

const Box48: TCBox; code; external;

const Line43: TCLine; code; external;

var   EveScrollBar37_OnPress: TEvent;        external;
var   EveScrollBar37:         TEveScrollbar; external;

var   Label48_Caption: string[11]; external;
var   Label48:         TLabel;     external;

var   EveScrollBar41_OnPress: TEvent;        external;
var   EveScrollBar41:         TEveScrollbar; external;

var   Label54_Caption: string[8]; external;
var   Label54:         TLabel;    external;

var   EveScrollBarGMupper1_OnPress: TEvent;        external;
var   EveScrollBarGMupper1:         TEveScrollbar; external;

var   Label58_Caption: string[8]; external;
var   Label58:         TLabel;    external;

var   EveScrollBar57_OnPress: TEvent;        external;
var   EveScrollBar57:         TEveScrollbar; external;

var   Label59_Caption: string[9]; external;
var   Label59:         TLabel;    external;

var   EveScrollBar58_OnPress: TEvent;        external;
var   EveScrollBar58:         TEveScrollbar; external;

var   Label60_Caption: string[8]; external;
var   Label60:         TLabel;    external;

var   EveScrollBarGMupper2_OnPress: TEvent;        external;
var   EveScrollBarGMupper2:         TEveScrollbar; external;

var   Label61_Caption: string[8]; external;
var   Label61:         TLabel;    external;

var   EveScrollBar60_OnPress: TEvent;        external;
var   EveScrollBar60:         TEveScrollbar; external;

var   Label62_Caption: string[11]; external;
var   Label62:         TLabel;     external;

const Label63_Caption: string[14]; code; external;
const Label63:         TCLabel;    code; external;

const Box49: TCBox; code; external;

var   ButtonRound119_Caption: string[8];     external;
var   ButtonRound119_OnDown:  TEvent;        external;
var   ButtonRound119:         TButton_Round; external;

var   ButtonRound120_Caption: string[8];     external;
var   ButtonRound120_OnDown:  TEvent;        external;
var   ButtonRound120:         TButton_Round; external;

var   CircleButtonDecUpr1_Caption: string[1];     external;
var   CircleButtonDecUpr1_OnDown:  TEvent;        external;
var   CircleButtonDecUpr1:         TCircleButton; external;

var   CircleButtonDecUpr2_Caption: string[1];     external;
var   CircleButtonDecUpr2_OnDown:  TEvent;        external;
var   CircleButtonDecUpr2:         TCircleButton; external;

var   CircleButtonIncUpr1_Caption: string[1];     external;
var   CircleButtonIncUpr1_OnDown:  TEvent;        external;
var   CircleButtonIncUpr1:         TCircleButton; external;

var   CircleButtonIncUpr2_Caption: string[1];     external;
var   CircleButtonIncUpr2_OnDown:  TEvent;        external;
var   CircleButtonIncUpr2:         TCircleButton; external;

var   ButtonRound121_Caption: string[8];     external;
var   ButtonRound121_OnDown:  TEvent;        external;
var   ButtonRound121:         TButton_Round; external;

const Box50: TCBox; code; external;

const Line45: TCLine; code; external;

var   Line46: TLine; external;

var   EveNumberGMupper1: TEveNumber; external;

var   EveNumberGMupper2: TEveNumber; external;

const Line44: TCLine; code; external;
const ScreenGMsynthUpr_Buttons_Round: array[009] of TButton_RoundPtr;  code; external;
const ScreenGMsynthUpr_Labels:        array[007] of TLabelPtr;         code; external;
const ScreenGMsynthUpr_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenGMsynthUpr_CircleButtons: array[004] of TCircleButtonPtr;  code; external;
const ScreenGMsynthUpr_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenGMsynthUpr_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenGMsynthUpr_Lines:         array[001] of TLinePtr;          code; external;
const ScreenGMsynthUpr_CLines:        array[003] of TCLinePtr;         code; external;
const ScreenGMsynthUpr_EveScrollBars: array[007] of TEveScrollbarPtr;  code; external;
const ScreenGMsynthUpr_EveNumbers:    array[002] of TEveNumberPtr;     code; external;


const ScreenGMsynthLwr_Buttons_Round: array[009] of TButton_RoundPtr;  code; external;
const ScreenGMsynthLwr_Labels:        array[007] of TLabelPtr;         code; external;
const ScreenGMsynthLwr_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenGMsynthLwr_CircleButtons: array[004] of TCircleButtonPtr;  code; external;
const ScreenGMsynthLwr_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenGMsynthLwr_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenGMsynthLwr_CLines:        array[004] of TCLinePtr;         code; external;
const ScreenGMsynthLwr_EveScrollBars: array[007] of TEveScrollbarPtr;  code; external;
const ScreenGMsynthLwr_EveNumbers:    array[002] of TEveNumberPtr;     code; external;

var   ScreenGMsynthLwr: TScreen; external;


var   Box43: TBox; external;

var   ButtonRound170_Caption: string[4];     external;
var   ButtonRound170_OnDown:  TEvent;        external;
var   ButtonRound170:         TButton_Round; external;

var   ButtonRound68_Caption: string[8];     external;
var   ButtonRound68_OnDown:  TEvent;        external;
var   ButtonRound68:         TButton_Round; external;

var   ButtonRound59_Caption: string[7];     external;
var   ButtonRound59_OnDown:  TEvent;        external;
var   ButtonRound59:         TButton_Round; external;

var   ButtonRound58_Caption: string[8];     external;
var   ButtonRound58_OnDown:  TEvent;        external;
var   ButtonRound58:         TButton_Round; external;

var   ButtonRound57_Caption: string[4];     external;
var   ButtonRound57_OnDown:  TEvent;        external;
var   ButtonRound57:         TButton_Round; external;

var   ButtonRound55_Caption: string[7];     external;
var   ButtonRound55_OnDown:  TEvent;        external;
var   ButtonRound55:         TButton_Round; external;

const Box44: TCBox; code; external;

const Line39: TCLine; code; external;

var   EveScrollBar35_OnPress: TEvent;        external;
var   EveScrollBar35:         TEveScrollbar; external;

var   Label46_Caption: string[11]; external;
var   Label46:         TLabel;     external;

var   EveScrollBar36_OnPress: TEvent;        external;
var   EveScrollBar36:         TEveScrollbar; external;

var   Label47_Caption: string[8]; external;
var   Label47:         TLabel;    external;

var   EveScrollBar38_OnPress: TEvent;        external;
var   EveScrollBar38:         TEveScrollbar; external;

var   Label49_Caption: string[8]; external;
var   Label49:         TLabel;    external;

var   EveScrollBar39_OnPress: TEvent;        external;
var   EveScrollBar39:         TEveScrollbar; external;

var   Label50_Caption: string[9]; external;
var   Label50:         TLabel;    external;

var   EveScrollBar40_OnPress: TEvent;        external;
var   EveScrollBar40:         TEveScrollbar; external;

var   Label53_Caption: string[8]; external;
var   Label53:         TLabel;    external;

var   EveScrollBar54_OnPress: TEvent;        external;
var   EveScrollBar54:         TEveScrollbar; external;

var   Label55_Caption: string[8]; external;
var   Label55:         TLabel;    external;

var   EveScrollBar55_OnPress: TEvent;        external;
var   EveScrollBar55:         TEveScrollbar; external;

var   Label56_Caption: string[11]; external;
var   Label56:         TLabel;     external;

const Label57_Caption: string[14]; code; external;
const Label57:         TCLabel;    code; external;

const Box45: TCBox; code; external;

var   ButtonRound69_Caption: string[8];     external;
var   ButtonRound69_OnDown:  TEvent;        external;
var   ButtonRound69:         TButton_Round; external;

var   ButtonRound90_Caption: string[8];     external;
var   ButtonRound90_OnDown:  TEvent;        external;
var   ButtonRound90:         TButton_Round; external;

var   CircleButton1_Caption: string[1];     external;
var   CircleButton1_OnDown:  TEvent;        external;
var   CircleButton1:         TCircleButton; external;

var   CircleButton2_Caption: string[1];     external;
var   CircleButton2_OnDown:  TEvent;        external;
var   CircleButton2:         TCircleButton; external;

var   CircleButton3_Caption: string[1];     external;
var   CircleButton3_OnDown:  TEvent;        external;
var   CircleButton3:         TCircleButton; external;

var   CircleButton4_Caption: string[1];     external;
var   CircleButton4_OnDown:  TEvent;        external;
var   CircleButton4:         TCircleButton; external;

var   ButtonRound101_Caption: string[8];     external;
var   ButtonRound101_OnDown:  TEvent;        external;
var   ButtonRound101:         TButton_Round; external;

const Box46: TCBox; code; external;

const Line41: TCLine; code; external;

const Line42: TCLine; code; external;

var   EveNumber1: TEveNumber; external;

var   EveNumber2: TEveNumber; external;

const Line40: TCLine; code; external;
const ScreenGMsynthLwr_Buttons_Round: array[009] of TButton_RoundPtr;  code; external;
const ScreenGMsynthLwr_Labels:        array[007] of TLabelPtr;         code; external;
const ScreenGMsynthLwr_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenGMsynthLwr_CircleButtons: array[004] of TCircleButtonPtr;  code; external;
const ScreenGMsynthLwr_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenGMsynthLwr_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenGMsynthLwr_CLines:        array[004] of TCLinePtr;         code; external;
const ScreenGMsynthLwr_EveScrollBars: array[007] of TEveScrollbarPtr;  code; external;
const ScreenGMsynthLwr_EveNumbers:    array[002] of TEveNumberPtr;     code; external;


const ScreenGMsynthPed_Buttons_Round: array[009] of TButton_RoundPtr;  code; external;
const ScreenGMsynthPed_Labels:        array[007] of TLabelPtr;         code; external;
const ScreenGMsynthPed_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenGMsynthPed_CircleButtons: array[004] of TCircleButtonPtr;  code; external;
const ScreenGMsynthPed_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenGMsynthPed_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenGMsynthPed_CLines:        array[004] of TCLinePtr;         code; external;
const ScreenGMsynthPed_EveScrollBars: array[007] of TEveScrollbarPtr;  code; external;
const ScreenGMsynthPed_EveNumbers:    array[002] of TEveNumberPtr;     code; external;

var   ScreenGMsynthPed: TScreen; external;


var   Box51: TBox; external;

var   ButtonRound171_Caption: string[4];     external;
var   ButtonRound171_OnDown:  TEvent;        external;
var   ButtonRound171:         TButton_Round; external;

var   ButtonRound136_Caption: string[8];     external;
var   ButtonRound136_OnDown:  TEvent;        external;
var   ButtonRound136:         TButton_Round; external;

var   ButtonRound135_Caption: string[7];     external;
var   ButtonRound135_OnDown:  TEvent;        external;
var   ButtonRound135:         TButton_Round; external;

var   ButtonRound134_Caption: string[8];     external;
var   ButtonRound134_OnDown:  TEvent;        external;
var   ButtonRound134:         TButton_Round; external;

var   ButtonRound133_Caption: string[4];     external;
var   ButtonRound133_OnDown:  TEvent;        external;
var   ButtonRound133:         TButton_Round; external;

var   ButtonRound122_Caption: string[7];     external;
var   ButtonRound122_OnDown:  TEvent;        external;
var   ButtonRound122:         TButton_Round; external;

const Box52: TCBox; code; external;

const Line47: TCLine; code; external;

var   EveScrollBar61_OnPress: TEvent;        external;
var   EveScrollBar61:         TEveScrollbar; external;

var   Label64_Caption: string[11]; external;
var   Label64:         TLabel;     external;

var   EveScrollBar62_OnPress: TEvent;        external;
var   EveScrollBar62:         TEveScrollbar; external;

var   Label65_Caption: string[8]; external;
var   Label65:         TLabel;    external;

var   EveScrollBar63_OnPress: TEvent;        external;
var   EveScrollBar63:         TEveScrollbar; external;

var   Label66_Caption: string[8]; external;
var   Label66:         TLabel;    external;

var   EveScrollBar64_OnPress: TEvent;        external;
var   EveScrollBar64:         TEveScrollbar; external;

var   Label67_Caption: string[9]; external;
var   Label67:         TLabel;    external;

var   EveScrollBar65_OnPress: TEvent;        external;
var   EveScrollBar65:         TEveScrollbar; external;

var   Label68_Caption: string[8]; external;
var   Label68:         TLabel;    external;

var   EveScrollBar66_OnPress: TEvent;        external;
var   EveScrollBar66:         TEveScrollbar; external;

var   Label69_Caption: string[8]; external;
var   Label69:         TLabel;    external;

var   EveScrollBar67_OnPress: TEvent;        external;
var   EveScrollBar67:         TEveScrollbar; external;

var   Label70_Caption: string[11]; external;
var   Label70:         TLabel;     external;

const Label71_Caption: string[14]; code; external;
const Label71:         TCLabel;    code; external;

const Box53: TCBox; code; external;

var   ButtonRound137_Caption: string[8];     external;
var   ButtonRound137_OnDown:  TEvent;        external;
var   ButtonRound137:         TButton_Round; external;

var   ButtonRound149_Caption: string[8];     external;
var   ButtonRound149_OnDown:  TEvent;        external;
var   ButtonRound149:         TButton_Round; external;

var   CircleButton9_Caption: string[1];     external;
var   CircleButton9_OnDown:  TEvent;        external;
var   CircleButton9:         TCircleButton; external;

var   CircleButton10_Caption: string[1];     external;
var   CircleButton10_OnDown:  TEvent;        external;
var   CircleButton10:         TCircleButton; external;

var   CircleButton11_Caption: string[1];     external;
var   CircleButton11_OnDown:  TEvent;        external;
var   CircleButton11:         TCircleButton; external;

var   CircleButton12_Caption: string[1];     external;
var   CircleButton12_OnDown:  TEvent;        external;
var   CircleButton12:         TCircleButton; external;

var   ButtonRound150_Caption: string[8];     external;
var   ButtonRound150_OnDown:  TEvent;        external;
var   ButtonRound150:         TButton_Round; external;

const Box54: TCBox; code; external;

const Line49: TCLine; code; external;

const Line50: TCLine; code; external;

var   EveNumber3: TEveNumber; external;

var   EveNumber4: TEveNumber; external;

const Line48: TCLine; code; external;
const ScreenGMsynthPed_Buttons_Round: array[009] of TButton_RoundPtr;  code; external;
const ScreenGMsynthPed_Labels:        array[007] of TLabelPtr;         code; external;
const ScreenGMsynthPed_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenGMsynthPed_CircleButtons: array[004] of TCircleButtonPtr;  code; external;
const ScreenGMsynthPed_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenGMsynthPed_CBoxes:        array[003] of TCBoxPtr;          code; external;
const ScreenGMsynthPed_CLines:        array[004] of TCLinePtr;         code; external;
const ScreenGMsynthPed_EveScrollBars: array[007] of TEveScrollbarPtr;  code; external;
const ScreenGMsynthPed_EveNumbers:    array[002] of TEveNumberPtr;     code; external;


const ScreenPresets_Buttons_Round: array[010] of TButton_RoundPtr;  code; external;
const ScreenPresets_Labels:        array[004] of TLabelPtr;         code; external;
const ScreenPresets_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenPresets_CircleButtons: array[008] of TCircleButtonPtr;  code; external;
const ScreenPresets_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenPresets_CBoxes:        array[001] of TCBoxPtr;          code; external;
const ScreenPresets_CLines:        array[001] of TCLinePtr;         code; external;
const ScreenPresets_EveScrollBars: array[004] of TEveScrollbarPtr;  code; external;
const ScreenPresets_EveNumbers:    array[004] of TEveNumberPtr;     code; external;

var   ScreenPresets: TScreen; external;


var   Box55: TBox; external;

var   ButtonRound172_Caption: string[7];     external;
var   ButtonRound172_OnDown:  TEvent;        external;
var   ButtonRound172:         TButton_Round; external;

var   ButtonRound173_Caption: string[4];     external;
var   ButtonRound173_OnDown:  TEvent;        external;
var   ButtonRound173:         TButton_Round; external;

var   ButtonRound174_Caption: string[8];     external;
var   ButtonRound174_OnDown:  TEvent;        external;
var   ButtonRound174:         TButton_Round; external;

var   ButtonRound175_Caption: string[7];     external;
var   ButtonRound175_OnDown:  TEvent;        external;
var   ButtonRound175:         TButton_Round; external;

var   ButtonRound176_Caption: string[8];     external;
var   ButtonRound176_OnDown:  TEvent;        external;
var   ButtonRound176:         TButton_Round; external;

var   ButtonRound177_Caption: string[4];     external;
var   ButtonRound177_OnDown:  TEvent;        external;
var   ButtonRound177:         TButton_Round; external;

const Box56: TCBox; code; external;

const Line54: TCLine; code; external;

const Label80_Caption: string[14]; code; external;
const Label80:         TCLabel;    code; external;

var   EveScrollBar72_OnPress: TEvent;        external;
var   EveScrollBar72:         TEveScrollbar; external;

var   Label51_Caption: string[11]; external;
var   Label51:         TLabel;     external;

var   CircleButton5_Caption: string[1];     external;
var   CircleButton5_OnDown:  TEvent;        external;
var   CircleButton5:         TCircleButton; external;

var   CircleButton6_Caption: string[1];     external;
var   CircleButton6_OnDown:  TEvent;        external;
var   CircleButton6:         TCircleButton; external;

var   CircleButton7_Caption: string[1];     external;
var   CircleButton7_OnDown:  TEvent;        external;
var   CircleButton7:         TCircleButton; external;

var   CircleButton8_Caption: string[1];     external;
var   CircleButton8_OnDown:  TEvent;        external;
var   CircleButton8:         TCircleButton; external;

var   EveNumber5: TEveNumber; external;

var   EveNumber6: TEveNumber; external;

var   EveScrollBar71_OnPress: TEvent;        external;
var   EveScrollBar71:         TEveScrollbar; external;

var   Label81_Caption: string[11]; external;
var   Label81:         TLabel;     external;

var   CircleButton19_Caption: string[1];     external;
var   CircleButton19_OnDown:  TEvent;        external;
var   CircleButton19:         TCircleButton; external;

var   CircleButton20_Caption: string[1];     external;
var   CircleButton20_OnDown:  TEvent;        external;
var   CircleButton20:         TCircleButton; external;

var   EveNumber7: TEveNumber; external;

var   EveScrollBar74_OnPress: TEvent;        external;
var   EveScrollBar74:         TEveScrollbar; external;

var   Label82_Caption: string[13]; external;
var   Label82:         TLabel;     external;

var   CircleButton21_Caption: string[1];     external;
var   CircleButton21_OnDown:  TEvent;        external;
var   CircleButton21:         TCircleButton; external;

var   CircleButton22_Caption: string[1];     external;
var   CircleButton22_OnDown:  TEvent;        external;
var   CircleButton22:         TCircleButton; external;

var   EveNumber8: TEveNumber; external;

var   EveScrollBar73_OnPress: TEvent;        external;
var   EveScrollBar73:         TEveScrollbar; external;

var   Label79_Caption: string[11]; external;
var   Label79:         TLabel;     external;

var   ButtonRound178_Caption: string[10];    external;
var   ButtonRound178_OnDown:  TEvent;        external;
var   ButtonRound178:         TButton_Round; external;

var   ButtonRound179_Caption: string[10];    external;
var   ButtonRound179_OnDown:  TEvent;        external;
var   ButtonRound179:         TButton_Round; external;

var   ButtonRound180_Caption: string[10];    external;
var   ButtonRound180_OnDown:  TEvent;        external;
var   ButtonRound180:         TButton_Round; external;

var   ButtonRound181_Caption: string[11];    external;
var   ButtonRound181_OnDown:  TEvent;        external;
var   ButtonRound181:         TButton_Round; external;
const ScreenPresets_Buttons_Round: array[010] of TButton_RoundPtr;  code; external;
const ScreenPresets_Labels:        array[004] of TLabelPtr;         code; external;
const ScreenPresets_CLabels:       array[001] of TCLabelPtr;        code; external;
const ScreenPresets_CircleButtons: array[008] of TCircleButtonPtr;  code; external;
const ScreenPresets_Boxes:         array[001] of TBoxPtr;           code; external;
const ScreenPresets_CBoxes:        array[001] of TCBoxPtr;          code; external;
const ScreenPresets_CLines:        array[001] of TCLinePtr;         code; external;
const ScreenPresets_EveScrollBars: array[004] of TEveScrollbarPtr;  code; external;
const ScreenPresets_EveNumbers:    array[004] of TEveNumberPtr;     code; external;


var CurrentScreen: TScreenPtr; external;

// Table of object draw handlers
// Use object type constants to access coresponding object draw handler
const DrawHandlerTable: array[44] of TPointer; external;
// ~Table of draw handler pointers
